# Generated by Django 5.0.6 on 2024-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alert_user_alert_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
