# Generated by Django 5.0.6 on 2024-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_rename_code_unit_id_remove_recipe_ingredient_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="image1",
            new_name="image_1",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="image2",
            new_name="image_2",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="image3",
            new_name="image_3",
        ),
    ]
