# Generated by Django 5.0.6 on 2024-06-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0004_remove_recipe_bookmark_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_ingredient",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredient",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipe_step",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_step",
                to="recipes.recipe",
            ),
        ),
    ]
