# Generated by Django 5.0.6 on 2024-06-03 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipe_ingredient_recipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="image_1",
            new_name="main_image",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="image_3",
        ),
    ]
