# Generated by Django 5.0.6 on 2024-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_image_1_recipe_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'daily'), (2, 'healthy'), (3, 'desert'), (4, 'midnight_snack')], default=4),
            preserve_default=False,
        ),
    ]
