# Generated by Django 5.0.6 on 2024-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'daily'), (2, 'healthy'), (3, 'desert'), (4, 'midnight_snack'), (5, 'none')], default=5),
        ),
    ]
