# Generated by Django 5.0.6 on 2024-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0009_alter_recipe_main_image_alter_recipe_step_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="main_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
