# Generated by Django 5.0.6 on 2024-06-07 16:28

import django.db.models.deletion
import recipes.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0002_alter_ingredient_id"),
        ("recipes", "0011_alter_recipe_main_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe_step",
            name="order",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="main_image",
            field=models.ImageField(null=True, upload_to=recipes.utils.upload_image),
        ),
        migrations.CreateModel(
            name="Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "category",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "daily"),
                            (2, "healthy"),
                            (3, "desert"),
                            (4, "midnight_snack"),
                            (5, "none"),
                        ],
                        default=5,
                    ),
                ),
                ("story", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "main_image",
                    models.ImageField(null=True, upload_to=recipes.utils.upload_image),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "done"), (1, "write"), (2, "update")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Temp_recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "category",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "daily"),
                            (2, "healthy"),
                            (3, "desert"),
                            (4, "midnight_snack"),
                            (5, "none"),
                        ],
                        default=5,
                    ),
                ),
                ("story", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "main_image",
                    models.ImageField(
                        null=True, upload_to=recipes.utils.temp_upload_image
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "done"), (1, "write"), (2, "update")], default=1
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Temp_ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_unit_recipe_ingredients",
                        to="recipes.unit",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_ingredient",
                        to="recipes.temp_recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Temp_step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.PositiveIntegerField(null=True)),
                ("image", models.CharField(default=None, max_length=255, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_step",
                        to="recipes.temp_recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
