# Generated by Django 5.0.6 on 2024-06-10 14:38

import recipes.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0014_alter_recipe_step_image_alter_temp_step_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe_step",
            name="image",
            field=models.ImageField(
                null=True, upload_to=recipes.utils.upload_image_step
            ),
        ),
    ]
