# Generated by Django 5.0.6 on 2024-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, choices=[(False, 'Male'), (True, 'Female')], null=True),
        ),
    ]
