# Generated by Django 5.0.6 on 2024-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_alert_alter_user_social"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social",
        ),
        migrations.AddField(
            model_name="user",
            name="social_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_type",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
