# Generated by Django 5.0.6 on 2024-06-03 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_conut"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Conut",
            new_name="Count",
        ),
    ]
