# Generated by Django 5.0.6 on 2024-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_delete_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_refresh_token",
            name="token",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
