# Generated by Django 5.0.6 on 2024-06-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_refresh_token_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temp_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gender",
                    models.BooleanField(
                        blank=True,
                        choices=[(False, "Male"), (True, "Female")],
                        null=True,
                    ),
                ),
                ("age", models.PositiveIntegerField(default=None, null=True)),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("image", models.CharField(blank=True, null=True)),
                ("is_staff", models.BooleanField(blank=True, default=False, null=True)),
                ("is_login", models.BooleanField(blank=True, default=False, null=True)),
                ("is_alert", models.BooleanField(blank=True, default=True, null=True)),
                ("social_id", models.CharField(max_length=100, null=True, unique=True)),
                ("social_type", models.CharField(max_length=15, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, null=True),
        ),
    ]
