# Generated by Django 5.0.6 on 2024-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
