# Generated by Django 5.0.6 on 2024-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collabo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(default='Click', max_length=255),
        ),
    ]
